flaskr/__init__.py
from flask import Flask
import os


def create_app(test_config=None):
    # Configuration
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY="dev",
        MAX_CONTENT_LENGTH=2_000_000,
        AWS_S3_BUCKET_NAME="dev",
        ALLOWED_IMAGE_EXTENSIONS={"png", "jpg", "jpeg"},
        DATABASE=os.path.join(app.instance_path, "flaskr.sqlite"),
    )

    if test_config is None:
        # load the instance config, if it exists, when not testing
        app.config.from_pyfile("config.py", silent=True)
    else:
        # load the test config if passed in
        app.config.from_mapping(test_config)

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    from . import db

    db.init_app(app)

    from .blueprints import core, htmx

    app.register_blueprint(htmx.bp)
    app.register_blueprint(core.bp)

    return app

flaskr/blueprints/core.py
from flask import (
    Blueprint,
    render_template,
    request,
    redirect,
    url_for,
    flash,
    current_app,
)
from werkzeug.utils import secure_filename
from flaskr.db import get_db
import boto3
from boto3.s3.transfer import S3UploadFailedError
import tempfile
from PIL import Image, UnidentifiedImageError

bp = Blueprint("core", __name__, url_prefix="/")


def allowed_file(filename):
    return (
        "." in filename
        and filename.rsplit(".", 1)[1].lower()
        in current_app.config["ALLOWED_IMAGE_EXTENSIONS"]
    )


@bp.route("/")
def index():
    return render_template("index.html")


@bp.route("/upload_image", methods=["GET", "POST"])
def upload_image():
    if request.method != "POST":
        return redirect(url_for("core.index"))

    if "image" not in request.files:
        flash("We haven't receive your image!", "danger")

        return redirect(url_for("core.index"))

    keywords = request.form.get("keywords", "")
    file = request.files["image"]
    # If the user does not select a file, the browser submits an
    # empty file without a filename.
    if file.filename == "" or not (file and allowed_file(file.filename)):
        img_types = ", ".join(current_app.config["ALLOWED_IMAGE_EXTENSIONS"])
        flash(f"Sorry, but we only allow image types: {img_types}!", "warning")
    else:
        filename = secure_filename(file.filename)

        # Temporary save the file.
        tfile = tempfile.mktemp()
        file.save(tfile)

        # Check if the file is an image.
        try:
            im = Image.open(tfile)
            im_status = True
            im.close()
        except UnidentifiedImageError:
            im_status = False

        if not im_status:
            flash("Your image seems invalid!", "danger")

            return redirect(url_for("core.index"))

        # Upload to AWS S3 bucket.
        client = boto3.resource("s3")
        bucket = client.Bucket(current_app.config["AWS_S3_BUCKET_NAME"])
        bucket_obj = bucket.Object(filename)

        try:
            bucket_obj.upload_file(tfile)
        except S3UploadFailedError as err:
            flash(
                "We got an issue during the uploading of your image. Please try again!",
                "danger",
            )
            current_app.logger.error(
                f"Couldn't upload file {filename} to {bucket.name}\n{err}."
            )

            return redirect(url_for("core.index"))

        # Update the database.
        db = get_db()
        db.execute(
            "INSERT INTO image (keywords, bucket_name, object_key) VALUES (?, ?, ?)",
            (keywords, bucket.name, bucket_obj.key),
        )
        db.commit()

        flash("Image uploaded successfully!", "success")

    return redirect(url_for("core.index"))


@bp.errorhandler(413)
def uploaded_file_too_large(e):
    max_upload_size = round(current_app.config["MAX_CONTENT_LENGTH"] / 1_000_000, 2)
    flash(
        f"The image is too large for us to upload it! The maximun is {max_upload_size} MB",
        "danger",
    )

    return redirect(url_for("core.index"))

flaskr/blueprints/htmx.py
from flask import Blueprint, session, render_template, request
from flaskr.db import get_db
import boto3


bp = Blueprint("htmx", __name__, url_prefix="/htmx")


@bp.route("/search")
def search():
    # We reset the pagination.
    session["skip"] = 0
    session["keywords"] = request.args.get("keywords", "")

    return render_template("gallery.html")


@bp.route("/gallery")
def gallery():
    skip = session.get("skip", 0)

    # Filter
    cond_values = [f"%{keyword}%" for keyword in session.get("keywords", "").split(" ")]
    conds = " OR ".join(["keywords LIKE ?"] * len(cond_values))

    db = get_db()
    images = db.execute(
        f"SELECT * FROM image WHERE {conds} AND id > ? LIMIT ?", (*cond_values, skip, 4)
    ).fetchall()

    # Extract data from AWS S3.
    s3_client = boto3.client("s3")
    images = [
        {
            "id": image["id"],
            "url": s3_client.generate_presigned_url(
                "get_object",
                Params={"Bucket": image["bucket_name"], "Key": image["object_key"]},
                ExpiresIn=3600,
            ),
            "keywords": image["keywords"],
        }
        for image in images
    ]

    # We prepare the next pagination.
    session["skip"] = skip + len(images)

    return render_template("images.html", images=images)


@bp.route("/upload_image")
def upload_image():
    return render_template("upload_image.html")

flaskr/templates/gallery.html
<a class="button is-fullwidth"
   hx-get="{{ url_for("htmx.gallery") }}"
   hx-trigger="click, load"
   hx-swap="beforebegin">See More</a>

flaskr/templates/images.html
<div class="columns is-desktop">
    {% for image in images %}
        <div class="column" onclick="viewImage({{ image.id }})">
            <div class="card">
                <div class="card-image">
                    <figure class="image is-4by3" id="{{ image.id }}">
                        <img src="{{ image.url }}" alt="Updated by anonymous" />
                    </figure>
                </div>
                <div class="card-footer">
                    <a href="#" class="card-footer-item">{{ image.keywords }}</a>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

flaskr/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Andromeda Pixel</title>
        <meta name="description"
              content="A website to share pictures of the Adromeda galaxy.">
        <meta name="keywords" content="adromeda, galaxy">
        <meta name="author" content="Brady Fomegne">
        <link rel="icon"
              type="image/png"
              href="{{ url_for('static', filename='icons/space.png') }}">
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/bulmaswatch/0.8.1/solar/bulmaswatch.min.css"
              integrity="sha512-X0mieKvmbMvynTQnO6+xKgXotkpOwn0P1KracVaHBuJWz9tfPgAvAICs2V4jUqclYpy774TrWM9HDi6emyrAjQ=="
              crossorigin="anonymous"
              referrerpolicy="no-referrer" />
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.css">
        <link rel="stylesheet"
              href="{{ url_for('static', filename='css/base.css') }}">
    </head>
    <body>
        <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
            <div class="navbar-brand">
                <a class="navbar-item" href="/">
                    <img alt="space logo"
                         src="{{ url_for('static', filename='icons/space.png') }}" />
                    &nbsp;
                    <b>Andromeda Galaxy Discovery</b>
                </a>
                <a role="button"
                   class="navbar-burger"
                   aria-label="menu"
                   aria-expanded="false"
                   data-target="navbar-menu-bar">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>
        </nav>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="notification is-{{ category }}">
                        <button class="delete"></button>
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        <section class="section has-text-centered">
            <div class="content">
                <h1 class="has-text-white">Explore the Andromeda Galaxy!</h1>
                <p>Go through millions of photos of the Andromeda Galaxy, and don't forget to share your own photos with the world.</p>
            </div>
            <div class="container mt-5">
                <div class="field has-addons has-addons-centered">
                    <p class="control is-expanded has-icons-left">
                        <span class="icon is-left">
                            <i class="fas fa-rocket"></i>
                        </span>
                        <input class="input"
                               type="text"
                               placeholder="Enter any keywords that pass in your mind."
                               name="keywords"
                               hx-get="{{ url_for("htmx.search") }}"
                               hx-trigger="input changed delay:500ms, keyup[key=='Enter'], load"
                               hx-target="#search_results"
                               hx-indicator=".htmx-indicator">
                    </p>
                    <p class="control">
                        <a class="button is-success"
                           onclick="uploadImage()"
                           hx-trigger="click"
                           hx-get="{{ url_for("htmx.upload_image") }}"
                           hx-target="#modal-js-content"><i class="fas fa-upload"></i>&nbsp;</a>
                    </p>
                </div>
            </div>
            <hr />
        </section>
        <section class="section">
            <div class="htmx-indicator">
                <div class="columns">
                    <div class="column"></div>
                    <div class="column is-2">
                        <img alt="space loading icon"
                             src="{{ url_for('static', filename='icons/loading.png') }}" />
                        <progress class="progress" max="100"></progress>
                    </div>
                    <div class="column"></div>
                </div>
                <br />
            </div>
            <div id="search_results"></div>
        </section>
        <!-- Modal -->
        <div id="modal-js" class="modal">
            <div class="modal-background"></div>
            <div class="modal-content" id="modal-js-content"></div>
            <button class="modal-close is-large" aria-label="close"></button>
        </div>
        <footer class="footer">
            <div class="container">
                <div class="content has-text-centered">
                    <p>
                        <strong>Andromeda Galaxy Discovery</strong> by
                        <a href="https://github.com/pythonbrad" target="_blank">Brady Fomegne</a>.
                        <br>
                        Based on
                        <a href="https://jenil.github.io/bulmaswatch/" target="_blank">Bulmaswatch</a>.
                        <br>
                        The source code is licensed
                        <a href="https://opensource.org/licenses/mit-license.php"
                           target="_blank">MIT</a>.
                    </p>
                </div>
            </div>
        </footer>
        <script src="https://cdn.jsdelivr.net/npm/htmx.org@2.0.6/dist/htmx.min.js"></script>
        <script src="{{ url_for('static', filename='js/base.js') }}"></script>
    </body>
</html>

flaskr/templates/upload_image.html
<form class="section"
      action="{{ url_for("core.upload_image") }}"
      method="post"
      enctype="multipart/form-data">
    <h1 class="title">Upload your Andromeda Galaxy Photo</h1>
    <figure class="image is-64x64">
        <img alt="guardian"
             src="{{ url_for('static', filename='icons/guardian.png') }}" />
    </figure>
    <div class="notification is-warning">
        <strong>Attention:</strong> As a member of our Andromeda Galaxy community, we ask you to respect our values. Please ensure that the image you upload is related to the Andromeda Galaxy. Uploading irrelevant content may be considered an offense to our community spirit. Let's celebrate our shared passion together!
    </div>
    <div class="field">
        <label class="label">Keywords</label>
        <div class="control">
            <input class="input"
                   type="text"
                   name="keywords"
                   placeholder="Add some keywords that describe the image"
                   required>
        </div>
    </div>
    <div class="field">
        <label class="label">Upload Image</label>
        <div class="control">
            <input class="input" type="file" name="image" accept="image/*" required>
        </div>
    </div>
    <div class="field">
        <div class="control">
            <button class="button is-primary" type="submit">Submit</button>
        </div>
    </div>
</form>